version: '3'
services:
  ddns:
    container_name: nip.io
    image: gameframe.nip.io:latest
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - "53:53/udp"
      - "53:53/tcp"
      - "8086:8082/tcp"
    volumes:
       - ./pdns/bind:/etc/pdns/bind
